### ISSUE TITLE
Casos especiais

### ISSUE THREAD

**Issue by renancouto** [theuves/pluralizador.js#2]
Bom trabalho com essa lib, é realmente complicado cobrir todos os casos de pluralização em português.

Eu notei que não há plural para alguns casos especiais, tipo: `qualquer -> quaisquer`, `campus -> campi` (mais info [aqui](https://duvidas.dicio.com.br/plural-de-campus/)). Há planos de adicionar suporte pra esses?

**Comment by theuves** [comment]
Obrigado Renan,

Vou adicioná-los em breve a uma nova lista de exceções.

Na Wikipédia achei [outras palavras](https://pt.wikipedia.org/wiki/Plural#Regras_especiais) também que ainda não listei como exceções:

- `mal` -> `males`
- `cônsul` -> `cônsules`

Há ainda aqueles substantivos abundantes, que trazem dois plurais válidos, como `mel` que pode ser `méis` ou `meles` (um pouco estranho, mas okay).

***

Obs.: *Qualquer* é um pronome, mas creio que pode ter casos de uso como um substantivo.

**Comment by theuves** [comment]
O *qualquer* não foi adicionado pois é um pronome.

O suporte as outras palavras foi adicionado no PR #4 (@nolleto).

Publicado na versão 1.0.1.
